export const ingredientNames: Record<string, string> = {
  Wheat: "Trigo",
  Rice: "Arroz",
  Oats: "Aveia",
  Barley: "Cevada",
  Rye: "Centeio",
  Corn: "Milho",
  Millet: "Painço",
  Sorghum: "Sorgo",
  Quinoa: "Quinoa",
  Buckwheat: "Trigo-sarraceno",
  Spelt: "Espelta",
  Bulgur: "Bulgur",
  Couscous: "Cuscuz",
  Semolina: "Sêmola",
  "Bran Flakes": "Flocos de Farelo",
  Cornflakes: "Flocos de Milho",
  Muesli: "Muesli",
  Granola: "Granola",
  Polenta: "Polenta",
  Farro: "Farro",
  Amaranth: "Amaranto",
  "Wild Rice": "Arroz Selvagem",
  "Basmati Rice": "Arroz Basmati",
  "Jasmine Rice": "Arroz Jasmim",
  "Brown Rice": "Arroz Integral",
  Potato: "Batata",
  "Sweet Potato": "Batata-doce",
  Carrot: "Cenoura",
  Beetroot: "Beterraba",
  Turnip: "Nabo",
  Radish: "Rabanete",
  Cassava: "Mandioca",
  Yam: "Inhame",
  Parsnip: "Pastinaca",
  Ginger: "Gengibre",
  Turmeric: "Açafrão-da-terra",
  Taro: "Taro",
  Rutabaga: "Rutabaga",
  Horseradish: "Rábano",
  Jicama: "Jícama",
  Celeriac: "Aipo-rábano",
  Daikon: "Daikon",
  Broccoli: "Brócolos",
  Cauliflower: "Couve-flor",
  Spinach: "Espinafre",
  Lettuce: "Alface",
  Cabbage: "Couve",
  Kale: "Couve-galega",
  Zucchini: "Courgete",
  Cucumber: "Pepino",
  "Bell Pepper": "Pimento",
  Tomato: "Tomate",
  Eggplant: "Beringela",
  Onion: "Cebola",
  Garlic: "Alho",
  Leek: "Alho-francês",
  Asparagus: "Espargos",
  Celery: "Aipo",
  "Brussels Sprouts": "Couve-de-bruxelas",
  Artichoke: "Alcachofra",
  Okra: "Quiabo",
  Pumpkin: "Abóbora",
  Squash: "Abóbora",
  "Green Beans": "Feijão-verde",
  Peas: "Ervilhas",
  "Corn on the Cob": "Espiga de Milho",
  Mushroom: "Cogumelo",
  Fennel: "Funcho",
  Chard: "Acelga",
  Watercress: "Agrião",
  "Bok Choy": "Bok Choy",
  Endive: "Endívia",
  "Chicken Breast": "Peito de Frango",
  "Chicken Thigh": "Coxa de Frango",
  "Beef Steak": "Bife de Vaca",
  "Ground Beef": "Carne Picada",
  "Pork Chop": "Costeleta de Porco",
  "Pork Belly": "Barriga de Porco",
  Bacon: "Bacon",
  Ham: "Fiambre",
  "Lamb Chop": "Costeleta de Borrego",
  "Ground Lamb": "Borrego Picado",
  Turkey: "Peru",
  Duck: "Pato",
  Veal: "Vitela",
  Sausage: "Salsicha",
  "Chicken Wing": "Asa de Frango",
  "Beef Brisket": "Peito de Vaca",
  "Pork Loin": "Lombo de Porco",
  Rabbit: "Coelho",
  Venison: "Veado",
  "Chicken Liver": "Fígado de Frango",
  Apple: "Maçã",
  Banana: "Banana",
  Orange: "Laranja",
  Grape: "Uva",
  Strawberry: "Morango",
  Blueberry: "Mirtilo",
  Raspberry: "Framboesa",
  Mango: "Manga",
  Pineapple: "Ananás",
  Watermelon: "Melancia",
  Peach: "Pêssego",
  Pear: "Pera",
  Cherry: "Cereja",
  Plum: "Ameixa",
  Kiwi: "Kiwi",
  Lemon: "Limão",
  Lime: "Lima",
  Grapefruit: "Toranja",
  Pomegranate: "Romã",
  Papaya: "Papaia",
  Apricot: "Alperce",
  Fig: "Figo",
  Coconut: "Coco",
  Avocado: "Abacate",
  Blackberry: "Amora",
  Cranberry: "Arando",
  Melon: "Melão",
  Nectarine: "Nectarina",
  "Passion Fruit": "Maracujá",
  Guava: "Goiaba",
  "Chicken Egg": "Ovo de Galinha",
  "Duck Egg": "Ovo de Pato",
  "Quail Egg": "Ovo de Codorniz",
  "Goose Egg": "Ovo de Ganso",
  "Egg White": "Clara de Ovo",
  "Egg Yolk": "Gema de Ovo",
  Salmon: "Salmão",
  Tuna: "Atum",
  Cod: "Bacalhau",
  Trout: "Truta",
  Mackerel: "Cavala",
  Sardine: "Sardinha",
  Herring: "Arenque",
  Haddock: "Arinca",
  Tilapia: "Tilápia",
  "Sea Bass": "Robalo",
  Anchovy: "Anchova",
  Halibut: "Alabote",
  Snapper: "Pargo",
  Catfish: "Peixe-gato",
  Swordfish: "Espadarte",
  Shrimp: "Camarão",
  Crab: "Caranguejo",
  Lobster: "Lagosta",
  Mussel: "Mexilhão",
  Clam: "Amêijoa",
  Oyster: "Ostra",
  Scallop: "Vieira",
  Squid: "Lula",
  Octopus: "Polvo",
  Prawn: "Gamba",
  Lentils: "Lentilhas",
  Chickpeas: "Grão-de-bico",
  "Black Beans": "Feijão Preto",
  "Kidney Beans": "Feijão Encarnado",
  "Pinto Beans": "Feijão Pinto",
  Soybeans: "Soja",
  "Green Peas": "Ervilhas",
  "Fava Beans": "Favas",
  "Lima Beans": "Feijão-de-lima",
  "Navy Beans": "Feijão Branco",
  "Split Peas": "Ervilha Partida",
  Edamame: "Edamame",
  "Mung Beans": "Feijão Mungo",
  "Black-eyed Peas": "Feijão-frade",
  Milk: "Leite",
  Cheese: "Queijo",
  Butter: "Manteiga",
  Yogurt: "Iogurte",
  Cream: "Natas",
  "Sour Cream": "Natas Azedas",
  "Cottage Cheese": "Queijo Cottage",
  Mozzarella: "Mozzarella",
  Cheddar: "Cheddar",
  Parmesan: "Parmesão",
  Feta: "Feta",
  Ricotta: "Ricotta",
  "Greek Yogurt": "Iogurte Grego",
  "Whipping Cream": "Natas para Bater",
  Buttermilk: "Leitelho",
  "Cream Cheese": "Queijo Creme",
  "Olive Oil": "Azeite",
  "Sunflower Oil": "Óleo de Girassol",
  "Vegetable Oil": "Óleo Vegetal",
  "Coconut Oil": "Óleo de Coco",
  "Sesame Oil": "Óleo de Sésamo",
  "Canola Oil": "Óleo de Canola",
  "Peanut Oil": "Óleo de Amendoim",
  "Avocado Oil": "Óleo de Abacate",
  "Corn Oil": "Óleo de Milho",
  "Palm Oil": "Óleo de Palma",
  "White Sugar": "Açúcar Branco",
  "Brown Sugar": "Açúcar Mascavado",
  Honey: "Mel",
  "Maple Syrup": "Xarope de Ácer",
  Molasses: "Melaço",
  "Agave Syrup": "Xarope de Agave",
  "Powdered Sugar": "Açúcar em Pó",
  "Corn Syrup": "Xarope de Milho",
  Salt: "Sal",
  "Black Pepper": "Pimenta Preta",
  Cinnamon: "Canela",
  Cumin: "Cominhos",
  Paprika: "Paprica",
  Oregano: "Orégãos",
  Basil: "Manjericão",
  Thyme: "Tomilho",
  Rosemary: "Alecrim",
  Vanilla: "Baunilha",
  "Soy Sauce": "Molho de Soja",
  Vinegar: "Vinagre",
  Mustard: "Mostarda",
  Ketchup: "Ketchup",
  Mayonnaise: "Maionese",
  "Baking Soda": "Bicarbonato de Sódio",
  "Baking Powder": "Fermento em Pó",
  Yeast: "Levedura",
  "Cocoa Powder": "Cacau em Pó",
  Coffee: "Café",
  Tea: "Chá",
  Almonds: "Amêndoas",
  Walnuts: "Nozes",
  Cashews: "Cajus",
  Peanuts: "Amendoins",
  Pistachios: "Pistácios",
  "Chia Seeds": "Sementes de Chia",
  "Flax Seeds": "Sementes de Linhaça",
  "Sunflower Seeds": "Sementes de Girassol",
  Tofu: "Tofu",
};
